// <auto-generated />
namespace Com.ChatR.MsSqlProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_Setup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_Setup));
        
        string IMigrationMetadata.Id
        {
            get { return "201609031603083_initial_Setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
